Revise specialists concept types
Financial-Times/concept-rw-elasticsearch pull request #77
Opened 2024-09-11 14:21 UTC by asparuhft

# Description

## What

Revise specialists concept types

## Why

JIRA Ticket [UPPSF-5514](https://financialtimes.atlassian.net/browse/UPPSF-5514)

## Anything, in particular, you'd like to highlight to reviewers

Mention here sections of code which you would like reviewers to pay extra attention to .E.g

_Would appreciate a second pair of eyes on the test_  
_I am not quite sure how this bit works_  
_Is there a better library for doing x_  

## Scope and particulars of this PR (Please tick all that apply)

- [ ] Tech hygiene (dependency updating & other tech debt)
- [ ] Bug fix
- [ ] Feature
- [ ] Documentation
- [ ] Breaking change
- [x] Minor change (e.g. fixing a typo, adding config)

___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

[UPPSF-5514]: https://financialtimes.atlassian.net/browse/UPPSF-5514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-09-12 17:14 UTC, agrancharova approved these changes

2024-09-16 07:37 UTC, angelraynovft submitted a review, later dismissed

2024-09-19 14:17 UTC, agrancharova commented on helm/concept-rw-elasticsearch/templates/deployment.yaml
>          - name: ELASTICSEARCH_ENDPOINT
lets keep fta-brands and fta-genres in the configuration

2024-09-24 10:56 UTC, agrancharova requested changes
lets keep fta-brands and fta-genres in the configuration

2024-09-24 11:33 UTC, agrancharova submitted a review, later dismissed

2024-09-24 11:41 UTC, agrancharova submitted a review, later dismissed

2024-09-25 06:31 UTC, agrancharova approved these changes

2024-09-25 06:52 UTC, ManoelMilchev reviewed
This branch is 7 commits behind master, please rebase.

2024-09-25 07:06 UTC, asparuhft commented
> This branch is 7 commits behind master, please rebase.

Done. Thanks

2024-09-25 07:11 UTC, ManoelMilchev approved these changes

2024-09-25 07:11 UTC, agrancharova commented
Can you rebase, instead of merging, so we avoid the merge commit

2024-09-25 07:25 UTC, asparuhft commented
> Can you rebase, instead of merging, so we avoid the merge commit

Done

2024-09-25 10:30 UTC, merged